app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
platform_admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/
    options:
        expose: true
platform_user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user/
    options:
        expose: true